import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, CheckCircle2 } from "lucide-react";
import { formatCurrency, formatDate } from "@/lib/format";
import { getOrder } from "@/services/order-service";
import { getCurrentUser } from "@/services/user-service";

export const metadata = { title: "Order details", robots: { index: false, follow: false } };
export default async function OrderPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ placed?: string }> }) { const user = await getCurrentUser(); if (!user) redirect("/login?next=/orders"); const id = (await params).id; const order = await getOrder(id, user.id, user.role === "admin").catch(() => null); if (!order) notFound(); const placed = (await searchParams).placed === "true"; return <div className="app-page shell"><Link href="/orders" className="back-link"><ArrowLeft size={16} /> Back to orders</Link>{placed && <div className="order-confirmation"><CheckCircle2 /><div><strong>Demo order confirmed</strong><span>No real payment was processed.</span></div></div>}<header className="app-page__header order-detail-header"><div><span className="eyebrow">ORDER #{order.orderNumber}</span><h1>{formatDate(order.createdAt)}</h1></div><span className="status-pill">{order.status}</span></header><div className="two-column"><section className="panel"><h2>Items</h2><div className="stack">{order.items.map((item) => <div className="order-detail-item" key={item.bookId}><div><Link href={`/books/${item.slug}`}><strong>{item.title}</strong></Link><span>{item.author} · Qty {item.quantity}</span></div><strong>{formatCurrency(item.priceAtPurchase * item.quantity)}</strong></div>)}</div><div className="order-totals"><div className="summary-row"><span>Subtotal</span><strong>{formatCurrency(order.subtotal)}</strong></div><div className="summary-row"><span>Shipping</span><strong>{order.shipping ? formatCurrency(order.shipping) : "Free"}</strong></div><div className="summary-row summary-row--total"><span>Total</span><strong>{formatCurrency(order.total)}</strong></div></div></section><aside className="stack"><section className="panel"><h2>Shipping information</h2><address>{order.shippingAddress.name}<br />{order.shippingAddress.addressLine1}<br />{order.shippingAddress.addressLine2 && <>{order.shippingAddress.addressLine2}<br /></>}{order.shippingAddress.city}, {order.shippingAddress.state} {order.shippingAddress.postalCode}<br />{order.shippingAddress.phone}</address></section><section className="panel"><h2>Payment</h2><p><span className="status-pill">Demo paid</span></p><p className="muted">Sandbox confirmation only. No real transaction or shipping tracking exists.</p></section></aside></div></div>; }
