"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import type { PublicUser } from "@/types";

export function ProfileForm({ user }: { user: PublicUser }) {
  const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(false); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); setError(!response.ok); setMessage(response.ok ? "Profile updated." : body.error?.message ?? "Unable to update profile."); if (response.ok) router.refresh(); } catch { setError(true); setMessage("Unable to update profile."); } finally { setPending(false); } }
  return <form onSubmit={submit}><div className="form-grid"><div className="form-field form-field--full"><label htmlFor="profile-name">Full name</label><input id="profile-name" name="name" defaultValue={user.name} required /></div><div className="form-field form-field--full"><label htmlFor="profile-email">Email</label><input id="profile-email" value={user.email} readOnly disabled /><small>Email changes are not supported in this demo.</small></div><div className="form-field"><label htmlFor="profile-phone">Phone</label><input id="profile-phone" name="phone" defaultValue={user.profile.phone} /></div><div className="form-field"><label htmlFor="profile-postal">Postal code</label><input id="profile-postal" name="postalCode" defaultValue={user.profile.postalCode} inputMode="numeric" /></div><div className="form-field form-field--full"><label htmlFor="profile-address1">Address</label><input id="profile-address1" name="addressLine1" defaultValue={user.profile.addressLine1} /></div><div className="form-field form-field--full"><label htmlFor="profile-address2">Address line 2</label><input id="profile-address2" name="addressLine2" defaultValue={user.profile.addressLine2} /></div><div className="form-field"><label htmlFor="profile-city">City</label><input id="profile-city" name="city" defaultValue={user.profile.city} /></div><div className="form-field"><label htmlFor="profile-state">State</label><input id="profile-state" name="state" defaultValue={user.profile.state} /></div></div>{message && <p className={error ? "form-error" : "form-success"} role="status">{message}</p>}<div className="form-actions"><button className="button button--primary" disabled={pending}>{pending ? "Saving…" : "Save profile"}</button></div></form>;
}

export function SecurityForm() {
  const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(false); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); if (data.get("newPassword") !== data.get("confirmPassword")) { setError(true); setMessage("New passwords do not match."); return; } setPending(true); setMessage(""); try { const response = await fetch("/api/profile/password", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentPassword: data.get("currentPassword"), newPassword: data.get("newPassword") }) }); const body = await response.json(); setError(!response.ok); setMessage(response.ok ? body.data.message : body.error?.message ?? "Unable to update password."); if (response.ok) { form.reset(); setTimeout(() => { router.push("/login"); router.refresh(); }, 900); } } catch { setError(true); setMessage("Unable to update password."); } finally { setPending(false); } }
  return <form onSubmit={submit}><div className="form-grid"><div className="form-field form-field--full"><label htmlFor="currentPassword">Current password</label><input id="currentPassword" name="currentPassword" type="password" autoComplete="current-password" required /></div><div className="form-field"><label htmlFor="newPassword">New password</label><input id="newPassword" name="newPassword" type="password" autoComplete="new-password" minLength={10} pattern="(?=.*[A-Za-z])(?=.*\d).{10,128}" required /></div><div className="form-field"><label htmlFor="confirmPassword">Confirm password</label><input id="confirmPassword" name="confirmPassword" type="password" autoComplete="new-password" minLength={10} required /></div></div>{message && <p className={error ? "form-error" : "form-success"} role="status">{message}</p>}<div className="form-actions"><button className="button button--primary" disabled={pending}>{pending ? "Updating…" : "Change password"}</button></div></form>;
}
