import Head from 'next/head'
import Image from 'next/image'

import Mid from '../components/Mid'

export default function Home() {
  return (
    <div >
      <Head>
        <title>NVBookstore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
    
    <div>
      <Image src='/book.jpg' alt='' height={3000} width={5000}/>
    </div>
    <Mid/>
    
    </div>
  )
}
