import Head from "next/head";
import Image from "next/image";

import Mid from "../components/Mid";

export default function Home() {
  return (
    <div className="dark:bg-gray-900">
      <Head>
        <title>NVBookstore</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>
      <div className="relative">
        <Image src="/book.jpg" alt="" height={3000} width={5000}  className=" opacity-30"/>
        {/* <div className="absolute top-1/3  w-full text-center  font-bold text-3xl text-orange-400 ">Welcome to the BookStore</div> */}
        <div className="type-bookstore absolute top-1/3  w-full text-center font-bold text-xl md:text-2xl lg:text-3xl text-orange-300"></div>
      </div>
     
      <Mid />
    </div>
  );
}
